from app import Category, Products, Users, db

category = [
    Category(id="1", name="GTA V", image_path="static/imgs/gta.png", cat_name="gta", starting_price="10", type="cat", status=""), 
    Category(id="2", name="APEX", image_path="static/imgs/apex.png", cat_name="apex", starting_price="10", type="cat", status=""),
    Category(id="3", name="TARKOV", image_path="static/imgs/tarkov.png", cat_name="tarkov", starting_price="10", type="cat", status=""),
    Category(id="4", name="DAYZ", image_path="static/imgs/dayz.png", cat_name="dayz", starting_price="10", type="cat", status=""),
    Category(id="5", name="DEAD BY DAYLIGHT", image_path="static/imgs/dead.png", cat_name="dead", starting_price="10", type="cat", status=""),
    Category(id="6", name="VALORANT", image_path="static/imgs/valorant.png", cat_name="valorant", starting_price="10", type="cat", status=""),
    Category(id="7", name="FIVEM", image_path="static/imgs/fivem.png", cat_name="fivem", starting_price="10", type="cat", status=""),
    Category(id="8", name="CYCLE", image_path="static/imgs/cycle.png", cat_name="cycle", starting_price="10", type="cat", status=""),
    Category(id="9", name="RUST", image_path="static/imgs/rust.png", cat_name="rust", starting_price="10", type="cat", status="")
]

products = [
    Products(id="1", name="GTA V", image_path="static/imgs/gta.png", cat_name="gta", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="2", name="APEX", image_path="static/imgs/apex.png", cat_name="apex", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}), 
    Products(id="3", name="TARKOV", image_path="static/imgs/tarkov.png", cat_name="tarkov", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}), 
    Products(id="4", name="DAYZ", image_path="static/imgs/dayz.png", cat_name="dayz", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}), 
    Products(id="5", name="DEAD BY DAYLIGHT", image_path="static/imgs/dead.png", cat_name="dead", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="6", name="VALORANT", image_path="static/imgs/valorant.png", cat_name="valorant", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="7", name="FIVEM", image_path="static/imgs/fivem.png", cat_name="fivem", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="8", name="CYCLE", image_path="static/imgs/cycle.png", cat_name="cycle", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="9", name="RUST FULL", image_path="static/imgs/rust.png", cat_name="rust", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],}),
    Products(id="10", name="RUST LITE", image_path="static/imgs/rust.png", cat_name="rust", type="product", description="Grazie a questo cheat potrai cheatare nel tuo gioco preferito!", status="Undetected", screens={"1": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg", "2": "https://ring-1.io/uploads/apex-1-62d9fa4e0fcd2025956931.jpg"}, requirements={"1": ["CPU:", "Intel only!"], "2": ["OS:", "Windows 10&11"], "3": ["Supported Anti-Cheat(s):", "BattlEye Anti-Cheat"]}, features={"AIM ASSIST": ["banane", "pesce"],"MISC": ["noci", "mandorle"]}, sub_type={"1": ["5", "7 Giorni"], "2": ["15", "30 Giorni"], "3": ["25", "2 Mesi"], "4": ["100", "6 Mesi"], "5": ["500", "1 Anno"],})
]


users = [
    Users(id="1", username="test", password="suca", is_auth=False)
]

for i in products:
    db.session.add(i)
    db.session.commit()

